### ISSUE TITLE
Add Swarm container to project.

### ISSUE THREAD

**Issue by egoralvolk** [javahippie/geth-dev#12]
Swarm is commonly used storage platform. Can you add Swarm container to project?

**Comment by javahippie** [comment]
I like the idea and will try to make some time for this feature. If somebody would like to work on this in the meantime, it would be greatly appreciated ;)

**Comment by javahippie** [comment]
We are talking about Ethereum Swarm. You are right about Docker Swarm, this is nothing that should be put on the agenda in 2018 ;)

**Comment by kyriediculous** [comment]
Just like the pemade geth docker image the same exists for swarm. 

https://hub.docker.com/r/ethdevops/

I'm actually looking into integrating swarm with your solution right now but I'm a complete docker and bash noob, sadly. 

Here's a couple of things though:
Each node needs a different -bzzport (tcp) but the udp port needs to be different as well from the default (30399) for subsequent nodes ran locally. This can be done with the flag --port.

Additionally we'll likely have to set 
--bzzapi "0.0.0.0"
-corsdomain "*" 
-httpaddr "0.0.0.0"

as well.

One last thing we'll need is a datadir

**Comment by javahippie** [comment]
@egoralvolk There are now Docker Swarm Nodes in the `develop` branch, would you mind giving it a try?

**Comment by javahippie** [comment]
Closed with the latest release: https://github.com/javahippie/geth-dev/releases/tag/geth-1.8.17
