### ISSUE TITLE
account password?

### ISSUE THREAD

**Issue by drandreaskrueger** [javahippie/geth-dev#14]
s.th.'s wrong with the password?

```
geth attach http://localhost:8545

Welcome to the Geth JavaScript console!
instance: Geth/v1.8.13-stable-225171a4/linux-amd64/go1.10.3
coinbase: 0x8cc5a1a0802db41db826c2fcb72423744338dcb0
at block: 74 (Mon, 20 Aug 2018 14:31:46 BST)
 modules: eth:1.0 net:1.0 rpc:1.0 web3:1.0
```

> eth.accounts
["0x8cc5a1a0802db41db826c2fcb72423744338dcb0"]

> personal.unlockAccount("0x8cc5a1a0802db41db826c2fcb72423744338dcb0")
Unlock account 0x8cc5a1a0802db41db826c2fcb72423744338dcb0
Passphrase: pass
Error: The method personal_unlockAccount does not exist/is not available

> personal.unlockAccount("0x8cc5a1a0802db41db826c2fcb72423744338dcb0")
Unlock account 0x8cc5a1a0802db41db826c2fcb72423744338dcb0
Passphrase: word
Error: The method personal_unlockAccount does not exist/is not available

> personal.unlockAccount("0x8cc5a1a0802db41db826c2fcb72423744338dcb0", "pass")
Error: The method personal_unlockAccount does not exist/is not available

> web3.personal
{
  listAccounts: undefined,
  ecRecover: function(),
  getListAccounts: function(callback),
  importRawKey: function(),
  lockAccount: function(),
  newAccount: function github.com/ethereum/go-ethereum/console.(*bridge).NewAccount-fm(),
  openWallet: function github.com/ethereum/go-ethereum/console.(*bridge).OpenWallet-fm(),
  sendTransaction: function(),
  sign: function github.com/ethereum/go-ethereum/console.(*bridge).Sign-fm(),
  unlockAccount: function github.com/ethereum/go-ethereum/console.(*bridge).UnlockAccount-fm()
}

> personal.unlockAccount
function github.com/ethereum/go-ethereum/console.(*bridge).UnlockAccount-fm()

**Comment by drandreaskrueger** [comment]
my workaround was to not even try to unlock, but that meant to [switch off the unlocking](https://gitlab.com/electronDLT/chainhammer/commit/5d3494ec0810e283cddc5881600099a15b0f1609) in my own code.

**Comment by drandreaskrueger** [comment]
> modules: eth:1.0 net:1.0 rpc:1.0 web3:1.0

might mean that not all rpc apis are accessible, right?

please by default open *all* those apis; this setup is not for production but for development only anyways, right?

**Comment by javahippie** [comment]
You do not need to unlock the account, as it is already unlocked by default in the Images. Geth is started with the `--unlock` flag.

**Comment by javahippie** [comment]
As I understand that it is not ideal to have all nodes automatically unlocked, would it help if the first node was unlocked by default and the other nodes needed to be unlocked via RPC?

**Comment by drandreaskrueger** [comment]
> You do not need to unlock the account

Yes, looks like case by case this differs. And in this case not. 

What if my standard chainhammer code always does that, at the beginning?

Looks like I really have to include all kind of situation specific exceptions, have a [look](https://gitlab.com/electronDLT/chainhammer/blob/master/clienttools.py#L67-92) = that is prone to future problems, though.

**Comment by drandreaskrueger** [comment]
> was unlocked by default and the other nodes needed to be unlocked via RPC

IMHO account unlocking should be done by the client, i.e. my chainhammer. Simply for not to seduce a coder into assuming any account is wide open. There is a `personal.unlockAccount()` call for that, and it works well (and even in parity with `parity --geth` switch).

BUT I think for this great dev tool that you are supplying us with .... I think all RPC APIs could be made accessible, not only  `eth:1.0 net:1.0 rpc:1.0 web3:1.0`

**Comment by javahippie** [comment]
I think you are right. Being auto unlocked is almost never a use case which is useful. 

I am happy that the tool is helpful! I will create another task to enable all RPC API, and try to update it asap.

**Comment by javahippie** [comment]
Changes merged in; accounts are no longer unlocked permanently.

**Comment by javahippie** [comment]
Unfortunately, for the clique consensus protocol the nodes need to be unlocked in order to start mining. I enabled the unlocking again for the miner-1 and miner-2, the node behind miner-3 is not mining anyways and can be used for all applications which need to unlock manually.

**Comment by drandreaskrueger** [comment]
> for the clique consensus protocol the nodes need to be unlocked in order to start mining.

Oh, oops ;-)

> which need to unlock manually.

All good as long as the `personal.unlockAccount()` function call is working. More a "which want to unlock manually" instead of "which need to unlock manually".

**Comment by drandreaskrueger** [comment]
one  more oops:

https://github.com/javahippie/geth-dev/blob/master/miner/Dockerfile#L27

your https://github.com/javahippie/geth-dev/commit/32c54558d481bebaaba715189c3d94ad5e4a7124 is not part of master yet?

**Comment by javahippie** [comment]
You are right. I am not sure what happened there, I committed the changes and merged to master

**Comment by drandreaskrueger** [comment]
perhaps forgot to git push  ?
