### ISSUE TITLE
Encrypted passwords

### ISSUE THREAD

**Issue by senzacionale** [javahippie/geth-dev#36]
I like your project but I would like to know if is possible to add encrypted passwords so that the project can be used in prod environment. 

Or just guve a hint how to encrypt password.

**Comment by javahippie** [comment]
For example, you could define the passwords as parameters in the [docker-compose.yml](https://docs.docker.com/compose/reference/) and pass it from the command line. Please be aware, that if you want to run the nodes as a public network, you would also need to change the nodes that are allowed to mine in the genesis block, and also the network ID should be changed.

I am hesitant to make those changes in the repository, as it would a) increase the complexity setting up the network and b) I don't want to tempt anyone into using this network for production, out of the box. Running a private (or even public) blockchain in production needs a lot of planning and insight, and I don't want any liability if this network is used as a template for this, hence the comments that this is meant for development only.

**Comment by senzacionale** [comment]
Hi. Thank you fir the response. 

Why I need to change the nodes to allow to mine in genesis block? I don’t want to mine anything. 

I know that was meant for dev only but I would like to use your template for prod as well.

**Comment by senzacionale** [comment]
I think is this one but not sure what is chainId of Kovan

```

{
  "config": {
    "chainId": 326432352,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "byzantiumBlock": 4,
    "clique": {
      "period": 5,
      "epoch": 30000
    }
  },
  "nonce": "0x0",
  "timestamp": "0x5a8efd25",
  "extraData": "0x00000000000000000000000000000000000000000000000000000000000000003590aca93338b0721966a8d0c96ebf2c4c87c5448cc5a1a0802db41db826c2fcb72423744338dcb00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0xf42400",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "3590aca93338b0721966a8d0c96ebf2c4c87c544": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    },
    "8cc5a1a0802db41db826c2fcb72423744338dcb0": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```

**Comment by javahippie** [comment]
Please keep the issues on topic.

Connecting this network to public test nets is not in the scope. I created it, because I did *not* want to connect to public test nets, and wanted a full featured option that was able to run locally.
