### ISSUE TITLE
miner-1 goes down after a couple of hours

### ISSUE THREAD

**Issue by inukaeth** [javahippie/geth-dev#39]
I am running this docker setup and I noticed that miner-1 goes down after leaving the setup overnight . This happens pretty consistently (latest pull, as well as the version a couple of weeks ago). When this happens the nodes are not responsive from the RPC apis, (transactions are not processed)

 I am not sure if this an issue with the configuration or an issue wtih Geth. 

 Thanks for posting up the project, was very useful.

**Comment by javahippie** [comment]
Hi inukaeth, thank you for your report!

Does it always only happen to miner-1, miner-2 is unaffected? Which operating system and Docker version are you running? Could you post the logs of your container here, if the node is not responsive anymore? You can take a look at them with `docker logs geth-miner-1`.

**Comment by javahippie** [comment]
Thank you for your answer! If you should find out that there is some kind of memory leak and it is not related to your machine, feel free to reopen this issue.

**Comment by inukaeth** [comment]
After reading a number threads regard the memory consumption in geth, some users reported the work around as to simply restart the node. To try this out I added  restart: always to each of the miners in the docker compose file, and that appears to have done the trick (Miner1 restarted after about an hour and has been up for 14+ hours so far). FYI , in case others hit this.
