### ISSUE TITLE
Unable to monitor blockchain nodes using blockchain-explorer

### ISSUE THREAD

**Issue by francisoud** [javahippie/geth-dev#49]
**Describe the bug**
After doing a docker-compose up
The blockchain-explorer doesn't work (or I don't know how to make it work)

**To Reproduce**
1. git clone https://github.com/javahippie/geth-dev.git
2. docker-compose up
3. go to http://localhost:8080
4. blockchain-explorer index page is displayed but spinners instead of data
5. click on Watch link and add the address define in https://github.com/javahippie/geth-dev/blob/master/docker-compose.yml#L60 (or any other address in docker compose) fails (javascript error in the browser console, the response is empty)

**Expected behavior**
obviously see the blockchain info in the blockchain-explorer

**Screenshots**
![screenshot from 2018-11-23 17-27-34](https://user-images.githubusercontent.com/23797/48953493-56559a80-ef46-11e8-8e17-8ae05411d3a0.png)
![screenshot from 2018-11-23 17-28-39](https://user-images.githubusercontent.com/23797/48953494-56559a80-ef46-11e8-837d-632dbe82c31c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome, firefox
 - docker --version: Docker version 18.09.0, build 4d60db4

**Additional context**
I tried to parse docker logs ...|grep "ERROR" didn't find anything

The miner and other nodes seems to be working (lots of verbose logs)
like:

```
geth-node           | DEBUG[11-23|16:38:03.003] Queued propagated block                  peer=2da72af06956b348 number=894 hash=01b63a…f39e4e queued=1
geth-node           | DEBUG[11-23|16:38:03.003] Importing propagated block               peer=2da72af06956b348 number=894 hash=01b63a…f39e4e
geth-node           | DEBUG[11-23|16:38:03.005] Trie cache stats after commit            misses=0 unloads=0
geth-node           | DEBUG[11-23|16:38:03.005] Dereferenced trie from memory database   nodes=0 size=0.00B time=4.16µs    gcnodes=0 gcsize=0.00B gctime=1.913655ms livenodes=1 livesize=0.00B
geth-node           | DEBUG[11-23|16:38:03.005] Inserted new block                       number=894 hash=01b63a…f39e4e uncles=0 txs=0 gas=0 elapsed=932.227µs
geth-node           | INFO [11-23|16:38:03.005] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=1.017ms     mgasps=0.000 number=894 hash=01b63a…f39e4e cache=0.00B
geth-node           | DEBUG[11-23|16:38:03.006] Reinjecting stale transactions           count=0
geth-node           | DEBUG[11-23|16:38:03.006] Queued propagated block                  peer=8d8877d4188d995f number=894 hash=01b63a…f39e4e queued=1
geth-miner-1        | DEBUG[11-23|16:38:03.003] Queued propagated block                  peer=2da72af06956b348 number=894 hash=01b63a…f39e4e queued=1
geth-miner-1        | DEBUG[11-23|16:38:03.003] Importing propagated block               peer=2da72af06956b348 number=894 hash=01b63a…f39e4e
geth-miner-1        | DEBUG[11-23|16:38:03.005] Trie cache stats after commit            misses=0 unloads=0
geth-miner-1        | DEBUG[11-23|16:38:03.005] Dereferenced trie from memory database   nodes=0 size=0.00B time=2.609µs  gcnodes=0 gcsize=0.00B gctime=1.52169ms  livenodes=1 livesize=0.00B
geth-miner-1        | DEBUG[11-23|16:38:03.005] Inserted new block                       number=894 hash=01b63a…f39e4e uncles=0 txs=0 gas=0 elapsed=921.142µs
geth-miner-1        | INFO [11-23|16:38:03.005] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=1.008ms   mgasps=0.000 number=894 hash=01b63a…f39e4e cache=0.00B
geth-miner-1        | DEBUG[11-23|16:38:03.006] Reinjecting stale transactions           count=0
geth-miner-1        | DEBUG[11-23|16:38:03.006] Queued propagated block                  peer=44b287eb858624b4 number=894 hash=01b63a…f39e4e queued=1
geth-miner-1        | INFO [11-23|16:38:03.006] 🔗 block reached canonical chain          number=887 hash=fb04c7…3f8c33
geth-miner-1        | INFO [11-23|16:38:03.006] Commit new mining work                   number=895 sealhash=92da4b…16b8ed uncles=0 txs=0 gas=0 fees=0 elapsed=397.539µs
geth-miner-2        | INFO [11-23|16:38:03.002] Successfully sealed new block            number=894 sealhash=940cb3…343250 hash=01b63a…f39e4e elapsed=4.995s
geth-miner-2        | INFO [11-23|16:38:03.002] 🔨 mined potential block                  number=894 hash=01b63a…f39e4e
geth-miner-2        | DEBUG[11-23|16:38:03.002] Reinjecting stale transactions           count=0
geth-miner-2        | INFO [11-23|16:38:03.004] Commit new mining work                   number=895 sealhash=f6d688…340efa uncles=0 txs=0 gas=0 fees=0 elapsed=1.489ms
geth-miner-2        | INFO [11-23|16:38:03.004] Signed recently, must wait for others 
geth-node           | DEBUG[11-23|16:38:03.971] Revalidated node                         b=16 id=8d5107cf4e03772d

```

**Comment by RobertoPirrone** [comment]
On the company firewall I had to open the 8545 port in output. in the explorer code there is this line:

web3 = new Web3(new Web3.providers.HttpProvider("http://knuckle-node.designisdead.io:8545"));
 
Hope it helps

**Comment by javahippie** [comment]
@francisoud Sorry for the late reply! It seems that the frontend is trying to connect to an external node. @kyriediculous You made a change to the explorer, not pointing to localhost but an online node, what's up with that? https://bitbucket.org/designisdead/blockchain-explorer/commits/3324edb9355ad9ad351d51d5c54e136249487f83

**Comment by javahippie** [comment]
@francisoud can you please retry after a new `git pull`? I created a workaround, resetting the explorer to an earlier version. I will keep this issue open, as it's not an ideal solution

**Comment by francisoud** [comment]
Much better thanks :+1:
May be you should use and commit the https://docs.npmjs.com/files/package-lock.json to fix dependencies but the way you did the workaround is fine also :)

**Comment by javahippie** [comment]
Thanks for the suggestion, I will look into it!
