### ISSUE TITLE
nodes are offline

### ISSUE THREAD

**Issue by grobi13** [javahippie/geth-dev#5]
What I have done:
- I have downloaded your master branch on 20.7.2018
- I stored it locally and called "docker-compose up" 
- all were established and running
- I can call the monitor on "localhost:3000"
- I can see the boot node and all 3 normal nodes; the status of the normal nodes is "offline"
- the containers for the normal node are up and running and have a running "geth" process 

My setup:
- Win10, Version 1803
- Docker 18.06 with Linux containers activated

Attached you can find the output after building all the images on starting all the containers and connect it.

[output.log](https://github.com/javahippie/geth-dev/files/2215203/output.log)

**Comment by javahippie** [comment]
It seems that the monitor backend is losing the connection to the nodes, due to some error:

```monitor-frontend         | 2018-07-20 19:39:28.082 [API] [CON] Connected gethDev1
monitor-backend          | 2018-07-20 19:39 +00:00: [wsc] =✓= The socket connection has been established.
monitor-backend          | 2018-07-20 19:39 +00:00: [eth] =i= { id: 'gethDev1',
monitor-backend          |   stats:
monitor-backend          |    { active: true,
monitor-backend          |      syncing: false,
monitor-backend          |      mining: true,
monitor-backend          |      hashrate: 0,
monitor-backend          |      peers: 2,
monitor-backend          |      gasPrice: '18000000000',
monitor-backend          |      uptime: 100 } }
monitor-frontend         | 2018-07-20 19:39:28.120 [API] [STA] Stats from: gethDev1
monitor-frontend         | 2018-07-20 19:39:28.127 [API] [BLK] Block: 1 from: gethDev1
monitor-backend          | /usr/local/lib/node_modules/pm2/node_modules/pidusage/lib/procfile.js:26
monitor-backend          |     buf = Buffer.alloc(SIZE)
monitor-backend          |                  ^
monitor-backend          |
monitor-backend          | TypeError: Buffer.alloc is not a function
monitor-backend          |     at readUntilEnd (/usr/local/lib/node_modules/pm2/node_modules/pidusage/lib/procfile.js:26:18)
monitor-backend          |     at /usr/local/lib/node_modules/pm2/node_modules/pidusage/lib/procfile.js:67:5
monitor-backend          |     at FSReqWrap.oncomplete (fs.js:82:15
```

If you connect to one of the nodes with `geth attach http://localhost:8545` and in the console call eth.getBlock('pending'), what does the output look like?

**Comment by javahippie** [comment]
I received the same error after pruning my Docker caches. It seems like pm2 (which is used to host the monitor backend application) was upgraded and had a new minimum node version. I updated the node versions in the Dockerfile, and the error did no longer appear for me. Can you please check, if the error is gone for you in the branch "issue-5-no-monitor-connection", too? 

https://github.com/javahippie/geth-dev/compare/issue-5-no-monitor-connection

**Comment by grobi13** [comment]
Hi @javahippie ,

great job! Everything works fine now. Thanks for the quick support!

**Comment by javahippie** [comment]
Very happy to hear that, thank you for taking your time to raise the issue!
